### ISSUE TITLE
Fix Dark/Light Mode for the Web App

### ISSUE THREAD

**Issue by akshaaatt** [akshaaatt/musicbrainz-web-next#8]
A toggle button is present at the settings in https://musicbrainz-web-next.vercel.app/profile but it isn't persistent throughout.

**Comment by amoghjalan** [comment]
I went through the code and found that:

1. Local Storage needs to be used to keep a check on the theme. As the website is server-side rendered the problem is getting created.
2. Currently we are passing theme prop to every component. I believe, making it globally valid would make the process easy.

@akshaaatt please let me know if the above is ok.
I'll proceed then.

**Comment by akshaaatt** [comment]
Agreed @amoghjalan 
I am in terms with what you said. Please proceed with the fix. Thanks!
